apiVersion: apps/v1
kind: Deployment
metadata:
 name: tetris
spec:
 replicas: 1
 selector:
   matchLabels:
     app: tetris
 template:
   metadata:
     labels:
       app: tetris
   spec:
     containers:
     - name: tetris
       image: doron/tetris
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: tetris
spec:
 type: LoadBalancer
 ports:
 - port: 80
   targetPort: 80
 selector:
   app: tetris
